<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>ExampleMod</AssemblyName>
        <Description>Example Mod</Description>
        <TargetFramework>net472</TargetFramework>
        <Version>1.0.0</Version>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <PublishRelease>true</PublishRelease>
        <NoWarn>MSB3277</NoWarn>


        <!-- todo macOS -->
        <GamePath Condition="'$(OS)' == 'Windows_NT'">C:/Program Files (x86)/Steam/steamapps/common/Hollow Knight</GamePath>
        <GamePath Condition="'$(OS)' != 'Windows_NT'">$(HOME)/.local/share/Steam/steamapps/common/Hollow Knight</GamePath>
        <DllPath>$(GamePath)/hollow_knight_Data/Managed</DllPath>

        <!-- If you're not using R2Modman/Thunderstore, this can be NineSolsPath as well. Only used in CopyDir -->
        <ProfileDir Condition="'$(OS)' == 'Windows_NT'">$(GamePath)</ProfileDir>
        <ProfileDir Condition="'$(OS)' != 'Windows_NT'">$(GamePath)</ProfileDir>
        <!-- After building, copy the dll to this folder. Useful for hot-reloading: https://github.com/BepInEx/BepInEx.Debug/blob/master/README.md#scriptengine -->
        <CopyDir>$(GamePath)/BepInEx/scripts</CopyDir>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(DllPath)/Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="PlayMaker">
            <HintPath>$(DllPath)/PlayMaker.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="../Resources/bundle.unity3d" />
        <Content Include="../Resources/bundle.objects.jsonc" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.*" />
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
        <PackageReference Include="UnityEngine.Modules" Version="2020.2.2" IncludeAssets="compile" />
    </ItemGroup>

    <Target Name="CopyMod" AfterTargets="PostBuildEvent" Condition="'$(CopyDir)' != ''">
        <Message Importance="high" Text="copying $(TargetPath) to $(CopyDir) ..." />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(CopyDir)" SkipUnchangedFiles="true" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(CopyDir)" SkipUnchangedFiles="true" />
    </Target>

    <Target Name="PackageMod" AfterTargets="Publish">
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="../thunderstore/build/dll" SkipUnchangedFiles="true" />
        <Exec Command="tcli build --config-path ../thunderstore/thunderstore.toml" />
    </Target>
</Project>
